### RELATÓRIO DOS TERMOS DE COMPROMISSOS EXECUTADOS NO ÂMBITO DO PRA

### Organização da base de dados

**Importação dos Pacotes Utilizados**

In [1]:
import pandas as pd
import plotly.express as px
import numpy as np
import plotly.graph_objects as go

Solicitação da base de dados e detalhamento da mesma:

In [29]:
data_df = pd.read_excel('Dados_TCA-Data.xlsx')

#data_df['Data_Termo_Compromisso']= pd.to_datetime(data_df['Data_Termo_Compromisso])

display(data_df.shape)
#display(data_df.describe())
display(data_df.head(10))

(364, 11)

,REC_CAR,NOME_IMOVEL,REGIAO_INTEGRACAO,MUNICIPIO,N_LICENCIAMENTOS,AREA_IMOVEL,AREA_RECOMPOR-RL,AREA_RECOMPOR-APP,AUR_Consolidada,Data_Termo_Compromisso,Hora_Termo_Compromisso
0,PA-1502707-A20C12BC35474120B59ABAB0C8DC63E6,Fazenda Três Lagoas,ARAGUAIA,Conceição do Araguaia,1,2589.8499,0.00000,76.83030,0.0,2019-08-23,09:01:43.672000
1,PA-1502764-15012AFEB9A74E02A43F578E33691332,Fazenda Princesa,ARAGUAIA,Cumaru do Norte,1,5387.7128,0.00000,363.14200,0.0,2021-07-08,12:51:30.669000
2,PA-1502764-6316EBD29FC048E09F81F2200BF04F99,FAZENDA CALIFORNIA,ARAGUAIA,Cumaru do Norte,1,2061.8963,158.31100,98.39090,0.0,2021-10-13,14:52:42.759000
3,PA-1502764-A501CE60588448A4B90F118561FCDE98,Fazenda Santa Ana (Lote 189),ARAGUAIA,Cumaru do Norte,0,5593.5331,21.61790,0.00000,0.0,2020-01-29,16:22:10.152000
4,PA-1502764-B4331FAB3EC04016A98BCDA6DD7AFA5E,FAZENDA VALE FORMOSO,ARAGUAIA,Cumaru do Norte,1,21987.0997,0.00000,284.72800,0.0,2021-06-15,11:00:35.965000
5,PA-1502764-C5085BB520E84BF3BD7CCAE42752319A,FAZENDA CARACOL,ARAGUAIA,Cumaru do Norte,1,3058.0358,0.46914,4.68548,0.0,2020-01-29,16:17:57.915000
6,PA-1502764-E0B3E87D0DE5449BB924123BC66017CE,Fazenda Santa Terezinha,ARAGUAIA,Cumaru do Norte,0,4007.2445,0.00000,89.71150,0.0,2021-07-14,18:32:37.775000
7,PA-1502764-FD09019815B742699303BFE07F4A28D3,FAZENDA CUMARU DO SUL,ARAGUAIA,Cumaru do Norte,1,9151.5012,0.00000,79.91550,0.0,2020-02-12,09:57:26.652000
8,PA-1502764-3DD6E4EF13384F989EAF04D1B81E4A23,Fazenda Rio Mudriré \nLTDA,ARAGUAIA,Cumaru do Norte,1,8866.0000,208.82680,322.23610,0.0,2021-12-09,NaN
9,PA-1502764- 350D2C698AC84E00AE51689C2309F267,Fazenda Santa Marta do Vale Verde,ARAGUAIA,Cumaru do Norte,1,48515.4200,39.99610,0.00000,0.0,2021-10-01,NaN

corri a coluna das datas:

In [30]:
data_TC = data_df['Data_Termo_Compromisso']
data_TC = pd.DataFrame({'Joined date': pd.to_datetime(data_TC)})
data_TC['Joined date']= pd.to_datetime(data_TC['Joined date']) 

data_df['Ano_Termo_Compromisso'] = data_TC['Joined date'].dt.year 
data_df['Mes_Termo_Compromisso'] = data_TC['Joined date'].dt.month 
display(data_df.head(10))

,REC_CAR,NOME_IMOVEL,REGIAO_INTEGRACAO,MUNICIPIO,N_LICENCIAMENTOS,AREA_IMOVEL,AREA_RECOMPOR-RL,AREA_RECOMPOR-APP,AUR_Consolidada,Data_Termo_Compromisso,Hora_Termo_Compromisso,Ano_Termo_Compromisso,Mes_Termo_Compromisso
0,PA-1502707-A20C12BC35474120B59ABAB0C8DC63E6,Fazenda Três Lagoas,ARAGUAIA,Conceição do Araguaia,1,2589.8499,0.00000,76.83030,0.0,2019-08-23,09:01:43.672000,2019.0,8.0
1,PA-1502764-15012AFEB9A74E02A43F578E33691332,Fazenda Princesa,ARAGUAIA,Cumaru do Norte,1,5387.7128,0.00000,363.14200,0.0,2021-07-08,12:51:30.669000,2021.0,7.0
2,PA-1502764-6316EBD29FC048E09F81F2200BF04F99,FAZENDA CALIFORNIA,ARAGUAIA,Cumaru do Norte,1,2061.8963,158.31100,98.39090,0.0,2021-10-13,14:52:42.759000,2021.0,10.0
3,PA-1502764-A501CE60588448A4B90F118561FCDE98,Fazenda Santa Ana (Lote 189),ARAGUAIA,Cumaru do Norte,0,5593.5331,21.61790,0.00000,0.0,2020-01-29,16:22:10.152000,2020.0,1.0
4,PA-1502764-B4331FAB3EC04016A98BCDA6DD7AFA5E,FAZENDA VALE FORMOSO,ARAGUAIA,Cumaru do Norte,1,21987.0997,0.00000,284.72800,0.0,2021-06-15,11:00:35.965000,2021.0,6.0
5,PA-1502764-C5085BB520E84BF3BD7CCAE42752319A,FAZENDA CARACOL,ARAGUAIA,Cumaru do Norte,1,3058.0358,0.46914,4.68548,0.0,2020-01-29,16:17:57.915000,2020.0,1.0
6,PA-1502764-E0B3E87D0DE5449BB924123BC66017CE,Fazenda Santa Terezinha,ARAGUAIA,Cumaru do Norte,0,4007.2445,0.00000,89.71150,0.0,2021-07-14,18:32:37.775000,2021.0,7.0
7,PA-1502764-FD09019815B742699303BFE07F4A28D3,FAZENDA CUMARU DO SUL,ARAGUAIA,Cumaru do Norte,1,9151.5012,0.00000,79.91550,0.0,2020-02-12,09:57:26.652000,2020.0,2.0
8,PA-1502764-3DD6E4EF13384F989EAF04D1B81E4A23,Fazenda Rio Mudriré \nLTDA,ARAGUAIA,Cumaru do Norte,1,8866.0000,208.82680,322.23610,0.0,2021-12-09,NaN,2021.0,12.0
9,PA-1502764- 350D2C698AC84E00AE51689C2309F267,Fazenda Santa Marta do Vale Verde,ARAGUAIA,Cumaru do Norte,1,48515.4200,39.99610,0.00000,0.0,2021-10-01,NaN,2021.0,10.0

Alteração no nome da coluna "REGIAO_INTEGRACAO" por "Região de Integração":

In [27]:
#data_df.rename(columns={"REGIAO_INTEGRACAO":"Região de Integração"})
#display(data_df.head(10))

Criando uma tabela dinâmica com a região de integração por número de Licenciamentos para descobrir o quantitativo de imóveis licenciados.

In [31]:
RegInt_Count = data_df[['REGIAO_INTEGRACAO','N_LICENCIAMENTOS']].value_counts()
RegInt_Count = pd.DataFrame(RegInt_Count, index = None)
RegInt_Count.sort_values(by='REGIAO_INTEGRACAO', ascending=True)
RegInt_Count.set_axis(['n° de Imovéis com Licencimento'], 
              axis='columns', inplace=True)

#Organizando o DataFrame por ordem alfabetica a coluna das regiões de integração: 
print(RegInt_Count.sort_values(by='REGIAO_INTEGRACAO', ascending=True))

#Exportando para excel o DataFrame criado:
RegInt_Count.to_excel (r'C:\Users\letic\Documents\Python Scripts\PRA TCA\RegInt_Count.xlsx', index = True, header=True)

                                    n° de Imovéis com Licencimento
REGIAO_INTEGRACAO N_LICENCIAMENTOS
ARAGUAIA          1                                             24
                  0                                             16
BAIXO AMAZONAS    1                                             37
                  0                                              5
CARAJÁS           1                                             10
                  0                                              6
GUAMÁ             1                                              4
LAGO DE TUCURUÍ   1                                              7
                  0                                              5
MARAJÓ            1                                              1
RIO CAPIM         1                                             53
                  0                                             21
TAPAJÓS           1                                             34
                  0                                              8
TOCANTINS         1                                             13
                  0                                              5
XINGU             0                                             18
                  1                                             97

In [ ]:
#x = [0]*len(RegInt_Count)
#j = 1
#for i in range(len(RegInt_Count)):
#    x[i] = j + i

#RegInt_Count=RegInt_Count.assign(Index = x)
#RegInt.set_index('Index', inplace = True)
#print(RegInt_Count)

Chamando o DataFrame exportado em excel e apresentado organizado por ordem alfabetica a região de integração:

In [32]:
dados = pd.read_excel('RegInt_Count.xlsx')
print(dados.sort_values(by=['REGIAO_INTEGRACAO']))
#display(dados)

   REGIAO_INTEGRACAO  N_LICENCIAMENTOS  n° de Imovéis com Licencimento
4           ARAGUAIA                 1                              24
7           ARAGUAIA                 0                              16
2     BAIXO AMAZONAS                 1                              37
15    BAIXO AMAZONAS                 0                               5
9            CARAJÁS                 1                              10
12           CARAJÁS                 0                               6
16             GUAMÁ                 1                               4
11   LAGO DE TUCURUÍ                 1                               7
13   LAGO DE TUCURUÍ                 0                               5
17            MARAJÓ                 1                               1
1          RIO CAPIM                 1                              53
5          RIO CAPIM                 0                              21
3            TAPAJÓS                 1                              34
10           TAPAJÓS                 0                               8
8          TOCANTINS                 1                              13
14         TOCANTINS                 0                               5
6              XINGU                 0                              18
0              XINGU                 1                              97

Para filtar apenas o quantitativo de imóveis com licenciamento, foi criado um dataframe selecionando apenas a linhas com valor igual a 1 na coluna "N_LICENCIAMENTOS", posteriormente foi excluida essa coluna e exportada para excel.

In [33]:
nImoveisLic = dados.loc[dados['N_LICENCIAMENTOS']==1]

nImoveisLic.drop(['N_LICENCIAMENTOS'], axis=1, inplace=True)

print(nImoveisLic.sort_values(by=['REGIAO_INTEGRACAO']))

nImoveisLic.to_excel (r'C:\Users\letic\Documents\Python Scripts\PRA TCA\N_Imoveis_Licenc.xlsx', index = False, header=True)

   REGIAO_INTEGRACAO  n° de Imovéis com Licencimento
4           ARAGUAIA                              24
2     BAIXO AMAZONAS                              37
9            CARAJÁS                              10
16             GUAMÁ                               4
11   LAGO DE TUCURUÍ                               7
17            MARAJÓ                               1
1          RIO CAPIM                              53
3            TAPAJÓS                              34
8          TOCANTINS                              13
0              XINGU                              97

C:\Users\letic\AppData\Local\Temp\ipykernel_5676\3876557460.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nImoveisLic.drop(['N_LICENCIAMENTOS'], axis=1, inplace=True)

Para saber o quantitativos de TCAs é necessário fazer a contagem de codigo de imóveis por região de integração, contudo aqui realizado a contagem de valores 1 e 0 de N_LICENCIAMENTOS por região de integração. Este dataframe foi criado, exportado em excel e chamado no algoritmo.

Logo em seguida foi criado um vetor com o nome das regiões de integração e organizados em ordem alfabetica.

Após a solicitação dos dados exportado em excel, foi selecioado apenas o valores igual a 1 na coluna N_LICENCIAMENTOS, excluida as colunas REGIAO_INTEGRACAO e N_LICENCIAMENTOS, acrescentao o vetor de região de integração criado anteriormente, renomeado as colunas para  'TCA' e 'Região de Integração', e por fim organizado as colunas do dataframe em 'Região de Integração' e 'TCA'.

In [34]:
tabTCA = dados.groupby(by=['REGIAO_INTEGRACAO','N_LICENCIAMENTOS']).sum().groupby(level=[0]).cumsum()
#print(tabTCA)

vetorRegiao_Int = dados['REGIAO_INTEGRACAO'].unique()
vetorRegiao_Int = vetorRegiao_Int.flatten().tolist()
vetorRegiao_Int = sorted(vetorRegiao_Int)

tabTCA.to_excel (r'C:\Users\letic\Documents\Python Scripts\PRA TCA\TCA_Regiao_Int.xlsx', index = True, header=True)

tca = pd.read_excel('TCA_Regiao_Int.xlsx')
#print(tca)
RegInt_TCA = tca.loc[tca['N_LICENCIAMENTOS']==1]
RegInt_TCA.drop(['REGIAO_INTEGRACAO','N_LICENCIAMENTOS'], axis=1, inplace=True)
RegInt_TCA['Região de Integração'] = vetorRegiao_Int
RegInt_TCA.set_axis(['TCA', 'Região de Integração'], axis='columns', inplace=True)
RegInt_TCA = RegInt_TCA[['Região de Integração','TCA']]
RegInt_TCA.to_excel (r'C:\Users\letic\Documents\Python Scripts\PRA TCA\TCA.xlsx', index = False, header=True)
print(RegInt_TCA)

   Região de Integração  TCA
1              ARAGUAIA   40
3        BAIXO AMAZONAS   42
5               CARAJÁS   16
6                 GUAMÁ    4
8       LAGO DE TUCURUÍ   12
9                MARAJÓ    1
11            RIO CAPIM   74
13              TAPAJÓS   42
15            TOCANTINS   18
17                XINGU  115

C:\Users\letic\AppData\Local\Temp\ipykernel_5676\1106896548.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  RegInt_TCA.drop(['REGIAO_INTEGRACAO','N_LICENCIAMENTOS'], axis=1, inplace=True)
C:\Users\letic\AppData\Local\Temp\ipykernel_5676\1106896548.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  RegInt_TCA['Região de Integração'] = vetorRegiao_Int

In [30]:
#tabela1 = data_df[['REGIAO_INTEGRACAO', 'N_LICENCIAMENTOS']]
#display(tabela1)

#### Agrupar os anos

#### Trabalhando com os outros dados da tabela

A primeira maneia de agrupar todos os valores das variáveis "AREA_IMOVEL", "AREA_RECOMPOR-APP", "AREA_RECOMPOR-RL" e "N_LICENCIAMENTOS", e utilizando a função *pivot_table*, como pode ser observado abaixo:

In [35]:
Area_Imoveis_df = pd.pivot_table(data_df, index=["REGIAO_INTEGRACAO"], values=['N_LICENCIAMENTOS',
                                                                               'AREA_IMOVEL','AREA_RECOMPOR-RL', 
                                                                               'AREA_RECOMPOR-APP'], aggfunc=[np.sum])
display(Area_Imoveis_df)

                           sum                                     \
                   AREA_IMOVEL AREA_RECOMPOR-APP AREA_RECOMPOR-RL
REGIAO_INTEGRACAO
ARAGUAIA           264847.6413        4166.43590       1760.97155
BAIXO AMAZONAS      23843.0330         116.76721        675.81088
CARAJÁS              6251.6351        1018.61628        201.82406
GUAMÁ                1583.4522          12.29543         69.96968
LAGO DE TUCURUÍ     50671.6292         603.33591       2862.67806
MARAJÓ               2189.2915           0.00000          0.00000
RIO CAPIM          214361.9940        2842.77102      10479.77424
TAPAJÓS             34330.0227         494.43152        324.88141
TOCANTINS           55591.0088         857.80152       1819.64155
XINGU               90441.5752        2152.19143       1865.07175


                  N_LICENCIAMENTOS
REGIAO_INTEGRACAO
ARAGUAIA                        24
BAIXO AMAZONAS                  37
CARAJÁS                         10
GUAMÁ                            4
LAGO DE TUCURUÍ                  7
MARAJÓ                           1
RIO CAPIM                       53
TAPAJÓS                         34
TOCANTINS                       13
XINGU                           97

Contudo, foi utilizado a função *groupby().sum()*. Em seguida foi excluida a coluna "AUR_Consolidada" por não utilizada no relatório e a coluna "N_LICENCIAMENTOS", pois já foi criada anteriomente (podendo ser utilizada essa também).

In [36]:
data_df2 = data_df.groupby('REGIAO_INTEGRACAO').sum()
data_df2.drop(['AUR_Consolidada', 'N_LICENCIAMENTOS', 'Ano_Termo_Compromisso', 'Mes_Termo_Compromisso'], axis=1, inplace=True)
display(data_df2)

                   AREA_IMOVEL  AREA_RECOMPOR-RL  AREA_RECOMPOR-APP
REGIAO_INTEGRACAO
ARAGUAIA           264847.6413        1760.97155         4166.43590
BAIXO AMAZONAS      23843.0330         675.81088          116.76721
CARAJÁS              6251.6351         201.82406         1018.61628
GUAMÁ                1583.4522          69.96968           12.29543
LAGO DE TUCURUÍ     50671.6292        2862.67806          603.33591
MARAJÓ               2189.2915           0.00000            0.00000
RIO CAPIM          214361.9940       10479.77424         2842.77102
TAPAJÓS             34330.0227         324.88141          494.43152
TOCANTINS           55591.0088        1819.64155          857.80152
XINGU               90441.5752        1865.07175         2152.19143

Os passos para organização dos dados foram:

* Criação de um index de 1 ao tamanho da tabela dinamica por região de integração;

* Acrescentar o vetor com nome dos municípios e um vetor com o index, criado no etapa anterior;

* Renomear a coluna do dataframe;

* Organizar as colunas.

In [37]:
#Criação de um index de 1 ao tamanho da tabela dinamica por região de integração
x = [0]*len(data_df2)
j = 1
for i in range(len(data_df2)):
    x[i] = j + i

#regInt = ['Araguai', 'Baixo Amazônas', 'Carajás', 'Guamá', 'Lago de Tucuruí',
#         'Marajó', 'Rio Capim', 'Tapajós', 'Tocantis', 'Xingu']

#Acrescentando o vetor com nome dos municípios e um vetor com o index, criado acima
new_df=data_df2.assign(Regiao_Integracao = vetorRegiao_Int, Index = x)
new_df.set_index('Index', inplace = True)

#Renomeado o dataframe
new_df.set_axis(['Área do Imóvel','Área a Recompor - RL', 
               'Área a Recompor - APP', 'Região de Integração'], 
              axis='columns', inplace=True)

#tab1.rename(columns={'REGIAO_INTEGRACAO':'Região de Integração',
#                     'N_LICENCIAMENTOS': 'Número de Licenciamentos', 'AREA_IMOVEL': 'Área do Imóvel',
#                           'AREA_RECOMPOR-RL':'Área a Recompor - RL', 'AREA_RECOMPOR-APP':'Área a Recompor - APP'}, 
#            inplace=True)

#Reorganizado as colunas
new_df = new_df.reindex(columns=['Região de Integração','Área do Imóvel','Área a Recompor - RL','Área a Recompor - APP'])
display(new_df)

new_df.to_excel (r'C:\Users\letic\Documents\Python Scripts\PRA TCA\Dados_TCA.xlsx', index = False, header=True)

,Região de Integração,Área do Imóvel,Área a Recompor - RL,Área a Recompor - APP
Index,,,,
1,ARAGUAIA,264847.6413,1760.97155,4166.43590
2,BAIXO AMAZONAS,23843.0330,675.81088,116.76721
3,CARAJÁS,6251.6351,201.82406,1018.61628
4,GUAMÁ,1583.4522,69.96968,12.29543
5,LAGO DE TUCURUÍ,50671.6292,2862.67806,603.33591
6,MARAJÓ,2189.2915,0.00000,0.00000
7,RIO CAPIM,214361.9940,10479.77424,2842.77102
8,TAPAJÓS,34330.0227,324.88141,494.43152
9,TOCANTINS,55591.0088,1819.64155,857.80152
10,XINGU,90441.5752,1865.07175,2152.19143

#### Unindo os dataframes

Para a finalização final da base de dados deve apenas unir os dataframes criados: *N_Imoveis_Licenc*, *TCA* e *Dados_TCA*.

In [38]:
N_Imoveis_Licenc = pd.read_excel('N_Imoveis_Licenc.xlsx')
N_Imoveis_Licenc.set_axis(['Região de Integração','n° de Imovéis com Licencimento'], axis='columns', inplace=True)
#print(N_Imoveis_Licenc)

TCA = pd.read_excel('TCA.xlsx')
TCA.set_axis(['Região de Integração','TCA'], axis='columns', inplace=True)
#print(TCA)

Dados_TCA = pd.read_excel('Dados_TCA.xlsx')
#display(Dados_TCA)

tab_dinamica = N_Imoveis_Licenc.merge(TCA, on = "Região de Integração", how = "left")
tab_dinamica = tab_dinamica.merge(Dados_TCA, on = "Região de Integração", how = "left")
tab_dinamica = tab_dinamica.sort_values(by=['Região de Integração'])
display(tab_dinamica)

tab_dinamica.to_excel (r'C:\Users\letic\Documents\Python Scripts\PRA TCA\Resultados\Geral\tab_dinamica_TCA.xlsx', index = False, header=True)

,Região de Integração,n° de Imovéis com Licencimento,TCA,Área do Imóvel,Área a Recompor - RL,Área a Recompor - APP
4,ARAGUAIA,24,40,264847.6413,1760.97155,4166.43590
2,BAIXO AMAZONAS,37,42,23843.0330,675.81088,116.76721
6,CARAJÁS,10,16,6251.6351,201.82406,1018.61628
8,GUAMÁ,4,4,1583.4522,69.96968,12.29543
7,LAGO DE TUCURUÍ,7,12,50671.6292,2862.67806,603.33591
9,MARAJÓ,1,1,2189.2915,0.00000,0.00000
1,RIO CAPIM,53,74,214361.9940,10479.77424,2842.77102
3,TAPAJÓS,34,42,34330.0227,324.88141,494.43152
5,TOCANTINS,13,18,55591.0088,1819.64155,857.80152
0,XINGU,97,115,90441.5752,1865.07175,2152.19143

In [39]:
Ano_BAIXO_AMAZONAS = data_df.loc[data_df['REGIAO_INTEGRACAO']=="BAIXO AMAZONAS"]
Ano_BAIXO_AMAZONAS.to_excel(r'C:\Users\letic\Documents\Python Scripts\PRA TCA\Dados_BAIXO_AMAZONAS.xlsx', index = False, header=True)
#display(Ano_BAIXO_AMAZONAS)

Ano_RIO_CAPIM = data_df.loc[data_df['REGIAO_INTEGRACAO']=="RIO CAPIM"]
Ano_RIO_CAPIM.to_excel(r'C:\Users\letic\Documents\Python Scripts\PRA TCA\Dados_RIO_CAPIM.xlsx', index = False, header=True)

Ano_TAPAJÓS = data_df.loc[data_df['REGIAO_INTEGRACAO']=="TAPAJÓS"]
Ano_TAPAJÓS.to_excel(r'C:\Users\letic\Documents\Python Scripts\PRA TCA\Dados_TAPAJÓS.xlsx', index = False, header=True)

Ano_XINGU = data_df.loc[data_df['REGIAO_INTEGRACAO']=="XINGU"]
Ano_XINGU.to_excel(r'C:\Users\letic\Documents\Python Scripts\PRA TCA\Dados_XINGU.xlsx', index = False, header=True)

#### Excluindo arquivos .xlsx desnecessários para não poluir o diretório

In [40]:
import os

if os.path.exists("N_Imoveis_Licenc.xlsx"):
  os.remove("N_Imoveis_Licenc.xlsx")

if os.path.exists("N_Imoveis_Licenc.xlsx"):
  os.remove("N_Imoveis_Licenc.xlsx")

if os.path.exists("TCA.xlsx"):
  os.remove("TCA.xlsx")

if os.path.exists("TCA_Regiao_Int.xlsx"):
  os.remove("TCA_Regiao_Int.xlsx")

if os.path.exists("RegInt_Count.xlsx"):
  os.remove("RegInt_Count.xlsx")